### ISSUE TITLE
`--reset-db` flag is not resetting the DB

### ISSUE THREAD

**Issue by petak5** [ProgrammingBuddies/programmingbuddies-api#27]
### Description
`--reset-db` flag should drop all tables that collide with actual DB layout or were removed from the code.
### How to reproduce
- Drop all tables (manually)
- Run the server
- Add a new model to the code (`testModel.py` with `Test` class for example)
- Import the model in `__init__.py` of the `models` folder
- Run the server - the newly added model should be added to the tables
- Remove the `Test` model and it's import from `__init__.py` of the `models` folder
- Run the server with `--reset-db` flag - the table representing `Test` is not dropped but it should be

**Comment by ghost** [comment]
This behaviour seems to conform to what the documentation says about drop_all
https://docs.sqlalchemy.org/en/13/core/metadata.html#creating-and-dropping-database-tables

db.drop_all can only drop tables it knows about. at the point where a model is removed from the init.py imports, the db object doesn't know about that model and subsequently cannot drop the table.

I am not sure creating a method which blindly drops all tables would be a good idea though.

I think since removing a model from the project shouls be a reare occurence we can live with removing the table manually in such a case.

**Comment by petak5** [comment]
Seems reasonable.

It should be mentioned this in the documentation (README) so people know they have to drop the table(s) manually if models are removed, tables renamed etc.

**Comment by ghost** [comment]
I'll implement that with some docs/error messages for the sqlalchemy part I still have to do.
I'll try to do it this evening.
