### ISSUE TITLE
Put app configuration in one place

### ISSUE THREAD

**Issue by ghost** [ProgrammingBuddies/programmingbuddies-api#75]
A lot of setup code is strewn across the project wildly.
they should be focused in one spot to make it easier to find/change

- [ ] database connection and sqlite check  in /api/models/database.py
- [ ]  /api/models/__init__.py
- - [ ] reset-db check in
- - [ ] commented out old test data in
- [ ] /api/views/oauthView.py
- - [ ] app secret
- - [ ] jwt_secret
- [ ] /api/__init__.py
- - [ ] json sort key

good place to put these might just be the runserver.py file where there are a bunch of other configs

**Comment by marter11** [comment]
I think we should put these configurations in a `config.py` file, because the `runserver.py` is only used in development, but in deployment maybe we also want to keep some configuration for example we are using a flask lib what handles the CORS and this needs some configuration what we may keep in deployment.
